// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/anuncios" | "/admin/dashboard" | "/admin/gestao" | "/admin/mini-pautas" | "/admin/relatorios" | "/admin/seguro" | "/admin/terminal-simulado" | "/admin/turmas" | "/aluno/terminal" | "/login" | "/login-admin" | "/login-prof" | "/pai/alterar-senha" | "/pai/anuncios" | "/pai/atividades" | "/pai/comprovante" | "/pai/comprovante/[id]" | "/pai/inicio" | "/pai/notas" | "/pai/notificacoes" | "/pai/pautas" | "/pai/perfil" | "/pai/seguro" | "/professor/anuncios" | "/professor/mini-pautas" | "/professor/notificar" | "/professor/turma" | "/validar/guia" | "/validar/guia/[guideNumber]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/pai" | "/professor"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/anuncios": {}
  "/admin/dashboard": {}
  "/admin/gestao": {}
  "/admin/mini-pautas": {}
  "/admin/relatorios": {}
  "/admin/seguro": {}
  "/admin/terminal-simulado": {}
  "/admin/turmas": {}
  "/aluno/terminal": {}
  "/login": {}
  "/login-admin": {}
  "/login-prof": {}
  "/pai": {}
  "/pai/alterar-senha": {}
  "/pai/anuncios": {}
  "/pai/atividades": {}
  "/pai/comprovante": {}
  "/pai/comprovante/[id]": { "id": string; }
  "/pai/inicio": {}
  "/pai/notas": {}
  "/pai/notificacoes": {}
  "/pai/pautas": {}
  "/pai/perfil": {}
  "/pai/seguro": {}
  "/professor": {}
  "/professor/anuncios": {}
  "/professor/mini-pautas": {}
  "/professor/notificar": {}
  "/professor/turma": {}
  "/validar/guia": {}
  "/validar/guia/[guideNumber]": { "guideNumber": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/pai": never
  "/professor": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
