// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/admin/anuncios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/anuncios">> = Specific
  const handler = {} as typeof import("../../../app/admin/anuncios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/gestao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/gestao">> = Specific
  const handler = {} as typeof import("../../../app/admin/gestao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/mini-pautas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/mini-pautas">> = Specific
  const handler = {} as typeof import("../../../app/admin/mini-pautas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/relatorios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/relatorios">> = Specific
  const handler = {} as typeof import("../../../app/admin/relatorios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/seguro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/seguro">> = Specific
  const handler = {} as typeof import("../../../app/admin/seguro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/terminal-simulado/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/terminal-simulado">> = Specific
  const handler = {} as typeof import("../../../app/admin/terminal-simulado/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/turmas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/turmas">> = Specific
  const handler = {} as typeof import("../../../app/admin/turmas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/aluno/terminal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/aluno/terminal">> = Specific
  const handler = {} as typeof import("../../../app/aluno/terminal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login-admin">> = Specific
  const handler = {} as typeof import("../../../app/login-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login-prof/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login-prof">> = Specific
  const handler = {} as typeof import("../../../app/login-prof/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/alterar-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pai/alterar-senha">> = Specific
  const handler = {} as typeof import("../../../app/pai/alterar-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/anuncios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pai/anuncios">> = Specific
  const handler = {} as typeof import("../../../app/pai/anuncios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/atividades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pai/atividades">> = Specific
  const handler = {} as typeof import("../../../app/pai/atividades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/comprovante/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pai/comprovante/[id]">> = Specific
  const handler = {} as typeof import("../../../app/pai/comprovante/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/comprovante/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pai/comprovante">> = Specific
  const handler = {} as typeof import("../../../app/pai/comprovante/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/inicio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pai/inicio">> = Specific
  const handler = {} as typeof import("../../../app/pai/inicio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/notas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pai/notas">> = Specific
  const handler = {} as typeof import("../../../app/pai/notas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/notificacoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pai/notificacoes">> = Specific
  const handler = {} as typeof import("../../../app/pai/notificacoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/pautas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pai/pautas">> = Specific
  const handler = {} as typeof import("../../../app/pai/pautas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pai/perfil">> = Specific
  const handler = {} as typeof import("../../../app/pai/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/seguro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pai/seguro">> = Specific
  const handler = {} as typeof import("../../../app/pai/seguro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/professor/anuncios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor/anuncios">> = Specific
  const handler = {} as typeof import("../../../app/professor/anuncios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/professor/mini-pautas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor/mini-pautas">> = Specific
  const handler = {} as typeof import("../../../app/professor/mini-pautas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/professor/notificar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor/notificar">> = Specific
  const handler = {} as typeof import("../../../app/professor/notificar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/professor/turma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/professor/turma">> = Specific
  const handler = {} as typeof import("../../../app/professor/turma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/validar/guia/[guideNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/validar/guia/[guideNumber]">> = Specific
  const handler = {} as typeof import("../../../app/validar/guia/[guideNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/validar/guia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/validar/guia">> = Specific
  const handler = {} as typeof import("../../../app/validar/guia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pai/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/pai">> = Specific
  const handler = {} as typeof import("../../../app/pai/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/professor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/professor">> = Specific
  const handler = {} as typeof import("../../../app/professor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
