import { Student, AccessLog, SchoolNotification, MedicalClinic, ClassAttendanceStat } from './types';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-1',
    matricula: '2026-00192',
    name: 'Lucas Silva',
    classId: '1a',
    className: '1º Ano A',
    schoolName: 'Colégio Futuro',
    parentName: 'Fernanda Silva',
    parentPhone: '+244 923 884 912',
    parentEmail: 'fernanda.silva@email.com',
    photoUrl: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=400&auto=format&fit=crop&q=80',
    status: 'present',
    lastEntryTime: '07:32:15',
    lastExitTime: undefined,
    biometricCode: 'BIO-FACIAL-99482-LUCAS',
    insurancePolicyId: 'SEG-ALO-2024-8821',
  },
  {
    id: 'std-2',
    matricula: '2026-00193',
    name: 'Beatriz Costa Santos',
    classId: '1a',
    className: '1º Ano A',
    schoolName: 'Colégio Futuro',
    parentName: 'Ricardo Santos',
    parentPhone: '+244 924 551 092',
    parentEmail: 'ricardo.santos@email.com',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    status: 'present',
    lastEntryTime: '07:25:02',
    lastExitTime: undefined,
    biometricCode: 'BIO-FACIAL-88319-BEATRIZ',
    insurancePolicyId: 'SEG-ALO-2024-8821',
  },
  {
    id: 'std-3',
    matricula: '2026-00194',
    name: 'Mateus Henrique Oliveira',
    classId: '1a',
    className: '1º Ano A',
    schoolName: 'Colégio Futuro',
    parentName: 'Juliana Oliveira',
    parentPhone: '+244 926 773 118',
    parentEmail: 'juliana.oliveira@email.com',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    status: 'absent',
    lastEntryTime: undefined,
    lastExitTime: undefined,
    biometricCode: 'BIO-FACIAL-77120-MATEUS',
    insurancePolicyId: 'SEG-ALO-2024-8821',
  },
  {
    id: 'std-4',
    matricula: '2026-00201',
    name: 'Rafael Mendes',
    classId: '2b',
    className: '2º Ano B',
    schoolName: 'Colégio Futuro',
    parentName: 'Carlos Mendes',
    parentPhone: '+244 923 119 443',
    parentEmail: 'carlos.mendes@email.com',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    status: 'present',
    lastEntryTime: '07:21:44',
    lastExitTime: undefined,
    biometricCode: 'BIO-FACIAL-66291-RAFAEL',
    insurancePolicyId: 'SEG-ALO-2024-8821',
  },
  {
    id: 'std-5',
    matricula: '2026-00202',
    name: 'Maria Eduarda Fernandes',
    classId: '2b',
    className: '2º Ano B',
    schoolName: 'Colégio Futuro',
    parentName: 'Helena Fernandes',
    parentPhone: '+244 925 338 901',
    parentEmail: 'helena.fernandes@email.com',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    status: 'present',
    lastEntryTime: '07:18:10',
    lastExitTime: undefined,
    biometricCode: 'BIO-FACIAL-55198-MARIA',
    insurancePolicyId: 'SEG-ALO-2024-8821',
  },
  {
    id: 'std-6',
    matricula: '2026-00305',
    name: 'Tiago Manuel Gonçalves',
    classId: '3c',
    className: '3º Ano C',
    schoolName: 'Colégio Futuro',
    parentName: 'Manuel Gonçalves',
    parentPhone: '+244 927 889 004',
    parentEmail: 'manuel.goncalves@email.com',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    status: 'absent',
    lastEntryTime: undefined,
    lastExitTime: undefined,
    biometricCode: 'BIO-FACIAL-44182-TIAGO',
    insurancePolicyId: 'SEG-ALO-2024-8821',
  },
  {
    id: 'std-7',
    matricula: '2026-00412',
    name: 'Ana Sofia Domingos',
    classId: '4a',
    className: '4º Ano A',
    schoolName: 'Colégio Futuro',
    parentName: 'Teresa Domingos',
    parentPhone: '+244 928 440 229',
    parentEmail: 'teresa.domingos@email.com',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    status: 'late',
    lastEntryTime: '08:05:12',
    lastExitTime: undefined,
    biometricCode: 'BIO-FACIAL-33190-ANA',
    insurancePolicyId: 'SEG-ALO-2024-8821',
  },
];

export const INITIAL_LOGS: AccessLog[] = [
  {
    id: 'log-1',
    studentId: 'std-1',
    studentName: 'Lucas Silva',
    studentPhoto: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=400&auto=format&fit=crop&q=80',
    className: '1º Ano A',
    schoolName: 'Colégio Futuro',
    type: 'entry',
    timestamp: '07:32:15',
    date: '20 de maio de 2026',
    location: 'Guarita Principal — Portaria 1',
    method: 'facial',
    receiptCode: 'CF-20260520-073215-A1',
    notified: true,
    notifiedRecipient: 'Fernanda Silva (Pai/Mãe)',
    statusNote: 'Pai Notificado via Push',
  },
  {
    id: 'log-2',
    studentId: 'std-2',
    studentName: 'Beatriz Costa Santos',
    studentPhoto: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    className: '1º Ano A',
    schoolName: 'Colégio Futuro',
    type: 'entry',
    timestamp: '07:25:02',
    date: '20 de maio de 2026',
    location: 'Guarita Principal — Portaria 1',
    method: 'facial',
    receiptCode: 'CF-20260520-072502-B2',
    notified: true,
    notifiedRecipient: 'Ricardo Santos (Pai/Mãe)',
    statusNote: 'Mãe Notificada via Push',
  },
  {
    id: 'log-3',
    studentId: 'std-4',
    studentName: 'Rafael Mendes',
    studentPhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    className: '2º Ano B',
    schoolName: 'Colégio Futuro',
    type: 'entry',
    timestamp: '07:21:44',
    date: '20 de maio de 2026',
    location: 'Guarita Principal — Portaria 1',
    method: 'facial',
    receiptCode: 'CF-20260520-072144-C3',
    notified: true,
    notifiedRecipient: 'Carlos Mendes (Pai/Mãe)',
    statusNote: 'Pai Notificado',
  },
  {
    id: 'log-4',
    studentId: 'std-5',
    studentName: 'Maria Eduarda Fernandes',
    studentPhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    className: '2º Ano B',
    schoolName: 'Colégio Futuro',
    type: 'entry',
    timestamp: '07:18:10',
    date: '20 de maio de 2026',
    location: 'Guarita Secundária — Bloco B',
    method: 'fingerprint',
    receiptCode: 'CF-20260520-071810-D4',
    notified: true,
    notifiedRecipient: 'Helena Fernandes',
    statusNote: 'Confirmado',
  },
];

export const INITIAL_NOTIFICATIONS: SchoolNotification[] = [
  {
    id: 'notif-1',
    type: 'access_entry',
    title: 'Entrada realizada',
    message: 'Lucas Silva entrou no Colégio Futuro às 07:32 via Reconhecimento Facial.',
    studentId: 'std-1',
    studentName: 'Lucas Silva',
    className: '1º Ano A',
    senderName: 'Terminal Biométrico Portaria 1',
    senderRole: 'Sistema Alô mãe',
    date: 'Hoje',
    time: '07:32',
    isRead: false,
    receiptCode: 'CF-20260520-073215-A1',
  },
  {
    id: 'notif-2',
    type: 'reunion',
    title: 'Convocação de Reunião de Pais',
    subject: 'Reunião de Avaliação do 3º Trimestre',
    message:
      'Estimados encarregados de educação, convidamos para a reunião trimestral de avaliação de desempenho pedagógico e atividades curriculares.',
    className: '1º Ano A',
    senderName: 'Profª. Maria Fernandes',
    senderRole: 'Professora Titular',
    date: 'Hoje',
    time: '08:15',
    reunionDate: '2026-10-08',
    reunionTime: '17:00',
    isRead: false,
  },
  {
    id: 'notif-3',
    type: 'praise',
    title: 'Elogio de Desempenho Escolar',
    subject: 'Participação Brilhante na Feira de Ciências',
    message:
      'Parabéns ao aluno Lucas Silva pela dedicação e excelente apresentação do projeto de sustentabilidade hídrica!',
    studentId: 'std-1',
    studentName: 'Lucas Silva',
    className: '1º Ano A',
    senderName: 'Coordenação Pedagógica',
    senderRole: 'Coordenação',
    date: 'Ontem',
    time: '15:40',
    isRead: true,
  },
  {
    id: 'notif-4',
    type: 'broadcast',
    title: 'Comunicado Geral da Direção',
    subject: 'Calendário de Provas & Seguro Escolar',
    message:
      'Informamos que todos os alunos estão com a apólice SEG-ALO-2024-8821 activa com cobertura hospitalar 24h nas clínicas parceiras.',
    senderName: 'Direção Geral',
    senderRole: 'Administração Escolar',
    date: '18 Mai',
    time: '11:20',
    isRead: true,
  },
];

export const MEDICAL_CLINICS: MedicalClinic[] = [
  {
    id: 'clin-1',
    name: 'Clínica Sagrada Família — Urgência Infantil',
    specialty: 'Clínica Pediátrica & Pronto Atendimento',
    address: 'Rua Rainha Ginga, nº 140 — Ingombota, Luanda',
    district: 'Ingombota',
    distanceKm: '1.8 km',
    timeMin: '5 min',
    emergencyPhone: '+244 923 111 222',
    services: ['Pediatria 24h', 'Traumatologia Infantil', 'Pronto Socorro', 'Ambulância UTI'],
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=400&auto=format&fit=crop&q=80',
    available24h: true,
  },
  {
    id: 'clin-2',
    name: 'Hospital Girassol — Unidade de Urgência',
    specialty: 'Hospital Geral & Centro Cirúrgico',
    address: 'Avenida Revolução de Outubro, Talatona — Luanda',
    district: 'Talatona',
    distanceKm: '4.2 km',
    timeMin: '12 min',
    emergencyPhone: '+244 923 990 000',
    services: ['Emergência Geral', 'Cirurgia Pediátrica', 'UTI Móvel', 'Radiologia Digital'],
    imageUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=400&auto=format&fit=crop&q=80',
    available24h: true,
  },
  {
    id: 'clin-3',
    name: 'Clínica Luanda Medical Center',
    specialty: 'Pronto Socorro 24h & Diagnóstico',
    address: 'Rua Amílcar Cabral, nº 58 — Maianga, Luanda',
    district: 'Maianga',
    distanceKm: '2.5 km',
    timeMin: '8 min',
    emergencyPhone: '+244 924 800 700',
    services: ['Pronto Atendimento', 'Exames de Sangue Rápidos', 'Sutura e Curativos'],
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=400&auto=format&fit=crop&q=80',
    available24h: true,
  },
  {
    id: 'clin-4',
    name: 'Centro de Ortopedia e Traumatologia Alô Care',
    specialty: 'Centro de Traumatologia & Ortopedia Escolar',
    address: 'Via AL15, Entrada Principal — Viana, Luanda',
    district: 'Viana',
    distanceKm: '6.1 km',
    timeMin: '15 min',
    emergencyPhone: '+244 912 888 999',
    services: ['Ortopedia Escolar', 'Raios-X Imediato', 'Imobilização de Fraturas'],
    imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=400&auto=format&fit=crop&q=80',
    available24h: true,
  },
];

export const CLASS_STATS: ClassAttendanceStat[] = [
  {
    classId: '1a',
    className: '1º Ano A',
    teacherName: 'Profª. Maria Fernandes',
    room: 'Sala 101',
    totalStudents: 30,
    presentsToday: 29,
    absentsToday: 1,
    latesToday: 0,
    monthlyPresents: 420,
    monthlyAbsences: 29,
    monthlyLates: 8,
    frequencyRate: 94,
  },
  {
    classId: '2b',
    className: '2º Ano B',
    teacherName: 'Prof. António Costa',
    room: 'Sala 104',
    totalStudents: 28,
    presentsToday: 28,
    absentsToday: 0,
    latesToday: 1,
    monthlyPresents: 420,
    monthlyAbsences: 24,
    monthlyLates: 8,
    frequencyRate: 95,
  },
  {
    classId: '3c',
    className: '3º Ano C',
    teacherName: 'Profª. Carla Ndalu',
    room: 'Sala 202',
    totalStudents: 32,
    presentsToday: 29,
    absentsToday: 3,
    latesToday: 2,
    monthlyPresents: 400,
    monthlyAbsences: 24,
    monthlyLates: 10,
    frequencyRate: 94,
  },
  {
    classId: '4a',
    className: '4º Ano A',
    teacherName: 'Prof. João Baptista',
    room: 'Sala 205',
    totalStudents: 25,
    presentsToday: 23,
    absentsToday: 2,
    latesToday: 1,
    monthlyPresents: 380,
    monthlyAbsences: 24,
    monthlyLates: 8,
    frequencyRate: 94,
  },
  {
    classId: '5a',
    className: '5º Ano A',
    teacherName: 'Profª. Teresa Varela',
    room: 'Sala 301',
    totalStudents: 25,
    presentsToday: 24,
    absentsToday: 1,
    latesToday: 0,
    monthlyPresents: 380,
    monthlyAbsences: 24,
    monthlyLates: 8,
    frequencyRate: 94,
  },
];

import { UserAccount } from './types';

export const MOCK_USERS: Record<string, UserAccount> = {
  pai: {
    uid: 'user-pai-1',
    id: 'user-pai-1',
    nome: 'Fernanda Silva',
    name: 'Fernanda Silva',
    email: 'fernanda.silva@email.com',
    telefone: '+244 923 884 912',
    phone: '+244 923 884 912',
    role: 'pai',
    criado_em: '2026-01-10T08:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    schoolName: 'Colégio Horizonte de Luanda',
    escola_nome: 'Colégio Horizonte de Luanda',
    title: 'Encarregada de Educação',
    studentId: 'std-1',
  },
  encarregado: {
    uid: 'user-pai-1',
    id: 'user-pai-1',
    nome: 'Fernanda Silva',
    name: 'Fernanda Silva',
    email: 'fernanda.silva@email.com',
    telefone: '+244 923 884 912',
    phone: '+244 923 884 912',
    role: 'encarregado',
    criado_em: '2026-01-10T08:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    schoolName: 'Colégio Horizonte de Luanda',
    escola_nome: 'Colégio Horizonte de Luanda',
    title: 'Encarregada de Educação',
    studentId: 'std-1',
  },
  professor: {
    uid: 'user-prof-1',
    id: 'user-prof-1',
    nome: 'Profª. Maria Fernandes',
    name: 'Profª. Maria Fernandes',
    email: 'maria.fernandes@colegiohorizonte.ao',
    telefone: '+244 912 340 556',
    phone: '+244 912 340 556',
    role: 'professor',
    criado_em: '2026-01-10T08:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1580894732488-82550bfa3f80?w=300&auto=format&fit=crop&q=80',
    schoolName: 'Colégio Horizonte de Luanda',
    escola_nome: 'Colégio Horizonte de Luanda',
    title: 'Docente Titular • 1º Ano A',
  },
  instituicao: {
    uid: 'user-admin-1',
    id: 'user-admin-1',
    nome: 'Dr. Carlos Manuel',
    name: 'Dr. Carlos Manuel',
    email: 'direcao@colegiohorizonte.ao',
    telefone: '+244 931 990 001',
    phone: '+244 931 990 001',
    role: 'instituicao',
    criado_em: '2026-01-10T08:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&auto=format&fit=crop&q=80',
    schoolName: 'Colégio Horizonte de Luanda',
    escola_nome: 'Colégio Horizonte de Luanda',
    title: 'Diretor Geral & Pedagógico',
  },
  admin: {
    uid: 'user-admin-1',
    id: 'user-admin-1',
    nome: 'Dr. Carlos Manuel',
    name: 'Dr. Carlos Manuel',
    email: 'direcao@colegiohorizonte.ao',
    telefone: '+244 931 990 001',
    phone: '+244 931 990 001',
    role: 'admin',
    criado_em: '2026-01-10T08:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&auto=format&fit=crop&q=80',
    schoolName: 'Colégio Horizonte de Luanda',
    escola_nome: 'Colégio Horizonte de Luanda',
    title: 'Diretor Geral & Pedagógico',
  },
};
